name: Continuous Integration
on:
  push:
  pull_request:
    branches:
     - master
  workflow_dispatch:
  schedule:
    # Artifacts expire every 90 days
    - cron: '53 05 01 * *'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            qt_arch: win64_msvc2022_64
            os_short: win
          - os: ubuntu-latest
            os_short: linux
          - os: macos-latest
            os_short: mac
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare short commit sha
        shell: bash
        run: echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Install dependencies (Linux)
        if: startsWith(runner.os, 'Linux')
        run: sudo apt-get update && sudo apt-get install -y libminiupnpc-dev libmaxminddb-dev

      - name: Install dependencies (macOS)
        if: startsWith(runner.os, 'macOS')
        run: brew install miniupnpc libmaxminddb

      - name: Install dependencies (Windows)
        if: startsWith(runner.os, 'Windows')
        run: vcpkg install miniupnpc libmaxminddb --triplet x64-windows-static-md

      - name: Configure MSVC
        if: startsWith(runner.os, 'Windows')
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          arch: ${{ matrix.qt_arch }}
          version: '6.9.0'

      - name: Configure
        if: "!startsWith(runner.os, 'Windows')"
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Configure (Windows)
        if: startsWith(runner.os, 'Windows')
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static-md

      - name: Build
        run: cmake --build build --config Release -j4

      - name: Package Linux
        if: startsWith(runner.os, 'Linux')
        shell: bash
        run: |
          mkdir -p package/lib/{platforms,xcbglintegrations}
          cp build/SourceAdminTool package
          cp GeoLite2-Country.mmdb app_list_map.ini commands.xml qt.conf package
          cp $QT_ROOT_DIR/lib/{libQt6Widgets.so.6,libQt6Gui.so.6,libQt6Network.so.6,libQt6Core.so.6,libQt6XcbQpa.so.6,libQt6DBus.so.6,libQt6OpenGL.so.6} package/lib || true
          cp $QT_ROOT_DIR/plugins/platforms/libqxcb.so package/lib/platforms || true
          cp $QT_ROOT_DIR/plugins/xcbglintegrations/*.so package/lib/xcbglintegrations || true
          cp -r $QT_ROOT_DIR/plugins/imageformats package/lib || true
      - name: Package macOS
        if: startsWith(runner.os, 'macOS')
        run: |
          macdeployqt build/SourceAdminTool.app
          mkdir package
          mv build/SourceAdminTool.app package
      - name: Package Windows
        if: startsWith(runner.os, 'Windows')
        run: |
          windeployqt --no-compiler-runtime --no-opengl-sw --no-system-d3d-compiler --no-translations --dir package build/Release/SourceAdminTool.exe
          Copy-Item GeoLite2-Country.mmdb,app_list_map.ini,commands.xml,build\Release\SourceAdminTool.exe -Destination package -PassThru

      - name: Create archive
        uses: actions/upload-artifact@v4
        with:
          name: SAT-${{ matrix.os_short }}-${{ env.GITHUB_SHA_SHORT }}
          path: package
